export enum Endpoints {
  getQuestions = "/questions",
  getSelf = "/auth/self",
  postQuestion = "/questions",
  postAnswer = "/answers",
  voteQuestion = "/votes/question",
  voteAnswer = "/votes/answer",
  getVoteStatusQuestion = "/votes",
  getVoteStatusAnswer = "/votes",
  getUser = "/users",
  searchTag = "/questions/tag",
  searchTitle = "/questions/title",
  getTags = "/tags",
  deleteQuestion = "/questions",
  deleteAnswer = "/answers",
  updateAnswer = "/answers",
}
